version: "3.8"

services: 
  postgres:
    container_name: listener-pay
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: listener-pay
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: listener-pay-cache
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - ./data/redis:/data